<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_The Buzz_fa fa-chevron-left</name>
   <tag></tag>
   <elementGuidId>a65cfa8b-ab7c-4fa7-a2b1-19612561a7e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/main/div[3]/div/div[2]/div[13]/div/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-chevron-left</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;content&quot;]/main[@class=&quot;main container-fluid&quot;]/div[@class=&quot;row related-content-and-products-container js-related-content-and-products-container&quot;]/div[@class=&quot;related-products js-related-products&quot;]/div[@class=&quot;related-products__container clearfix js-related-products-container&quot;]/div[@class=&quot;related-content js-related-content-slider&quot;]/div[@class=&quot;related-content__container js-related-content-container&quot;]/button[@class=&quot;slide-left js-slide-left&quot;]/i[@class=&quot;fa fa-chevron-left&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/div[3]/div/div[2]/div[13]/div/button/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/i</value>
   </webElementXpaths>
</WebElementEntity>
