<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_These Stylish Wall Sconces Instantly Elev_2105cf</name>
   <tag></tag>
   <elementGuidId>55811531-6408-4c1c-9d00-09ed0862a2ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/main/div[3]/div/div[2]/div[13]/div/button[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-chevron-right</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/main[@class=&quot;main container-fluid&quot;]/div[@class=&quot;row related-content-and-products-container js-related-content-and-products-container&quot;]/div[@class=&quot;related-products js-related-products&quot;]/div[@class=&quot;related-products__container clearfix js-related-products-container&quot;]/div[@class=&quot;related-content js-related-content-slider&quot;]/div[@class=&quot;related-content__container js-related-content-container&quot;]/button[@class=&quot;slide-right js-slide-right&quot;]/i[@class=&quot;fa fa-chevron-right&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/div[3]/div/div[2]/div[13]/div/button[2]/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/i</value>
   </webElementXpaths>
</WebElementEntity>
