<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//div[@class='no-results-box']//h1</description>
   <name>NoResultTitle</name>
   <tag></tag>
   <elementGuidId>44111614-4628-4cfe-87eb-9e0435a2cbe7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='no-results-box']//h1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
